### ISSUE TITLE
Having issue with Theme directory

### ISSUE THREAD

**Issue by cinetube** [laugmanuel/bludit-docker#3]
I made some changes to a bludit theme. But when I restarted the bludit container the customization I made on the theme directory vanished and the theme returned to its default state. 

How to resolve this issue?

**Comment by laugmanuel** [comment]
Hi @cinetube,
can you provide the way you run the image? Do you use the provided `docker-compose.yml` file? Which theme do you use?

**Comment by cinetube** [comment]
@laugmanuel I used the image you provided. Site is working fine. No existing posts are vanising. But with the restart of the container all the changes I made to the files in the theme folder vanished are resettled to default. 

I tried to modify "popeye' theme.

**Comment by laugmanuel** [comment]
This is due to the fact, the popeye theme is provided together with bludit and the container therefore updates the theme on startup (to be compatible with new bludit releases).
This should be fixed with #4

**Comment by cinetube** [comment]
> This is due to the fact, the popeye theme is provided together with bludit and the container therefore updates the theme on startup (to be compatible with new bludit releases). This should be fixed with #4

Thanks for the update.

**Comment by laugmanuel** [comment]
Just set `SKIP_THEMES_INSTALL` to `true` and restart the container. You should see that installation was skipped and you can modify the theme as you wish.
Just note that you might want to update the theme in the future because it might change and be incompatible with your old theme.

**Comment by laugmanuel** [comment]
fixed in #4
